### ISSUE TITLE
"genes_fasta" ignored?

### ISSUE THREAD

**Issue by kinzlaw** [FredHutch/gig-map#6]
Hi, Sam.
We've tried to run through all the 4 workflows, with an NCBI 350 genomes [prokaryotes.csv](https://drive.google.com/file/d/15rO0L0PUJ5NgglENMyn_gILkGL1idALo/view?usp=sharing)(the [original download link from NCBI](https://www.ncbi.nlm.nih.gov/genomes/solr2txt.cgi?q=%5Bdisplay()%5D.from(GenomeAssemblies).usingschema(%2Fschema%2FGenomeAssemblies).matching(tab%3D%3D%5B%22Prokaryotes%22%5D%20and%20level%3D%3D%5B%22Complete%22%5D%20and%20q%3D%3D%22Xanthomonas%22)&fields=organism%7COrganism%20Name%2Clineage%7COrganism%20Groups%2Cstrain%7CStrain%2Cbiosample%7CBioSample%2Cbioproject%7CBioProject%2Cassembly%7CAssembly%2Clevel%7CLevel%2Csize%7CSize(Mb)%2Cgc_content%7CGC%25%2Creplicons%7CReplicons%2Cwgs%7CWGS%2Cscaffolds%7CScaffolds%2Cproteins%7CCDS%2Crelease_date%7CRelease%20Date%2Cftp_path_genbank%7CGenBank%20FTP%2Cftp_path_refseq%7CRefSeq%20FTP&filename=prokaryotes.csv&nolimit=on) seems to have more genomes now), and 7 local fasta files(converted from unpublished .gb files generated by NCBI automatic annotation, they're converted [here](http://genome2d.molgenrug.nl/g2d_tools_conversions.html), using the `GenBank->Proteins` button) as input. And finally found our local sequences missing from the result, we don't know what's wrong, please help us, thanks in advance.
- Is it unsupported to use `genome_tables` and `genes_fasta` simultaneously?
- Did we provide the local fasta files in the wrong format?
- With the same prokaryotes.csv, when download.sh, gig-map downloaded 350 `fna.gz` files, but deduplicate.sh only downloaded 335/310(the number varied in different tries) `faa.gz` files, but the status progress all showed no error. Is this situation normal?

Our download.params.json
```
{
    "genome_tables": "prokaryotes-350.csv",
    "genes_fasta": "0307.faa.gz,0316.faa.gz,0609.faa.gz,XF10.faa.gz,XF2-1.faa.gz,XF2.faa.gz,Y12.faa.gz",
    "output_folder": "downloaded_genomes"
}
```

and deduplicate.params.json
```
{
    "genome_tables": "prokaryotes-350.csv",
    "genes_fasta": "0307.faa.gz,0316.faa.gz,0609.faa.gz,XF10.faa.gz,XF2-1.faa.gz,XF2.faa.gz,Y12.faa.gz",
    "output_folder": "downloaded_genes"
}
```

**Comment by sminot** [comment]
I'd love to help you troubleshoot the issue that you've encountered. In the meantime I should also let you know that I'm actively working on the `modularize` branch to implement an update which will make it easier to combine genes and genomes from multiple sources.

In the meantime, it would be great if you could post a summary of the error that you're encountering, as well as the version of the pipeline that you're running and the code you're using to invoke it. I should be able to get an idea there of what sort of issue is coming up.

**Comment by sminot** [comment]
After giving it some thought, I realized that the original implementation of `gig-map` was fundamentally inconvenient for combining sets of genes and genomes from different sources, as exemplified by the issue you note here. 

Rather than try to fix the original inconvenient implementation, I have instead tried to provide a new setup with allows you a much greater degree of flexibility in selecting genes and genomes for alignment.

You can now find the details and documentation for the new setup in the wiki.

I have also preserved the original implementation with the `0.1.0` tag, and so you can feel free to keep running your previous workflows. However, I would strongly suggest reading over the new implementation and seeing if you can more easily overcome this issue with the utilities provided there.
